### ISSUE TITLE
[Bug]: Plugin "@netlify/plugin-nextjs" internal error: ENOENT: no such file or directory with runtime 5.0.0-beta.7

### ISSUE THREAD

**Issue by caomicc** [netlify/next-runtime#2420]
### Summary

I'm having an issue with getting our site to run on the beta runtime. We are currently on next `13.4.1` and testing with `5.0.0-beta.7`

We are using turborepo for this site and have custom build settings in our `netlify.toml` to reflect that

Once committed, the deploy will build successfully and then fail after the `onBuild` with the following error:

```
11:15:26 AM: (@netlify/plugin-nextjs onEnd completed in 4ms)
11:15:27 AM: ​
11:15:27 AM: Plugin "@netlify/plugin-nextjs" internal error                
11:15:27 AM: ────────────────────────────────────────────────────────────────
11:15:27 AM: ​
11:15:27 AM:   Error message
11:15:27 AM:   Error: ENOENT: no such file or directory, open "/opt/build/repo/apps/web/required-server-files.json"
11:15:27 AM: ​
11:15:27 AM:   Plugin details
11:15:27 AM:   Package:        @netlify/plugin-nextjs
11:15:27 AM:   Version:        5.0.0-beta.7
11:15:27 AM:   Repository:     git+https://github.com/netlify/next-runtime-minimal.git
11:15:27 AM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-nextjs
11:15:27 AM:   Report issues:  https://github.com/netlify/next-runtime-minimal/issues
11:15:27 AM: ​
11:15:27 AM:   Error location
11:15:27 AM:   In "onBuild" event in "@netlify/plugin-nextjs" from netlify.toml and package.json
11:15:27 AM: ​
11:15:27 AM:   Error properties
11:15:27 AM:   {
11:15:27 AM:     errno: -2,
11:15:27 AM:     code: "ENOENT",
11:15:27 AM:     syscall: "open",
11:15:27 AM:     path: "/opt/build/repo/apps/web/required-server-files.json"
11:15:27 AM:   }
11:15:28 AM: Failed during stage "building site": Build script returned non-zero exit code: 4
11:15:28 AM: Build failed due to an internal system error: Build script returned non-zero exit code: 4
11:15:28 AM: Failing build: Failed to build site
11:15:28 AM: Finished processing build request in 4m29.05s
```

For what its worth, I did attempt to submit an issue on the requested links in that error, but was getting a 404.

I am wondering if the missing file is related to the monorepo?

Thanks!

### A link to a reproduction repository

https://app.netlify.com/sites/workhuman-next/deploys/65c25a12e9e90f000874c61a

### Expected Result

No internal errors + build to deploy successfully

### Actual Result

`Plugin "@netlify/plugin-nextjs" internal error`

### Steps to reproduce

1. Update to 5.0.0-beta.7 following documentation provided by Netlify Support
2. Build

### Next Runtime version

5.0.0-beta.7

### Is your issue related to the `app` directory?

- [ ] Yes, I am using the `app` directory

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### What OS are you using?

Mac OS

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>

```toml
# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  # If not set, defaults to the root directory.
  base = "apps/web"

  # The ignore command provides custom, programmatic control over builds.
  # We use this to check if the respective site has been changed or not.
  ignore = "npx turbo-ignore"

  # Directory that contains the deploy-ready HTML files and
  # assets generated by the build. This is relative to the base
  # directory if one has been set.
  # publish = ".next"

  # Turborepo build command. We exit the base folder to make sure we can
  # access the root directory where our turbo config is.
  command = "cd ../.. && npx turbo run build --filter=web..."

[functions]
  included_files = [

    "!../../node_modules/sharp/vendor/*",

    "!../../node_modules/@esbuild/*",

    "!../../node_modules/@esbuild/*",

    "!../../node_modules/@swc/core-linux-x64-musl/*",

    "!../../node_modules/@swc/core-linux-x64-gnu/*",

    "!../../node_modules/@swc/core-darwin-x64/*",

    "!../../node_modules/sharp/vendor/8.14.5/linux-x64/lib/libvips-cpp.so.42",

    "!../../node_modules/@esbuild/linux-x64/bin/esbuild",

    "!../../node_modules/esbuild/lib/downloaded-@esbuild-linux-x64-esbuild",

    "!../../node_modules/esbuild/lib/downloaded-@esbuild-linux-x64-esbuild",

    "!../../node_modules/@fortawesome/pro-regular-svg-icons/index.js",

    "!../../node_modules/@fortawesome/pro-solid-svg-icons/index.js",

  ]

[[redirects]]
  force = true
  from = "/munchkin.js"
  status = 200
  to = "https://862-jiq-698.mktoweb.com/munchkin.js"

[[redirects]]
  force = true
  from = "/uc.js"
  status = 200
  to = "https://consent.cookiebot.com/uc.js"

[[redirects]]
  force = true
  from = "/heap.js"
  status = 200
  to = "https://cdn.heapanalytics.com/js/heap-XXXXXX.js"

[[redirects]]
  force = true
  from = "/uwt.js"
  status = 200
  to = "https://static.ads-twitter.com/uwt.js"

[[edge_functions]]
  function = "add-slash"
  path = "/*"


[[plugins]]
  package = "@netlify/plugin-nextjs"

```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>

```
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>

```js
/** @type {import('next').NextConfig} */
const nextI18nConfig = require('./next-i18next.config');

module.exports = {
  swcMinify: true,
  reactStrictMode: true,
  transpilePackages: [
    '@workhumanweb/ui',
    '@workhumanweb/api',
    '@workhumanweb/algolia-indexing-job',
    '@workhumanweb/common-i18n',
  ],
  eslint: {
    dirs: ['.'],
  },
  poweredByHeader: false,
  trailingSlash: true,
  // experimental: {
  //   adjustFontFallbacks: true,
  // },
  experimental: {
    forceSwcTransforms: true,
    // nextScriptWorkers: true,
    scrollRestoration: true,
  },
  api: {
    bodyParser: false,
  },
  images: {
    // dangerouslyAllowSVG: true,
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
    domains: [
      'www.workhuman.com',
      'www.workhumanpreprod.com',
      'images.ctfassets.net',
      'netlify.app',
    ],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.ctfassets.net',
      },
    ],
  },
  env: {
    ...
  },
  i18n: nextI18nConfig.i18n,
  async headers() {
    ...
  },
  async rewrites() {
    return [
      {
        source: '/events/spotlight/:series',
        destination: '/spotlight-landing/:series',
      },
    ];
  },
};

```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>

```
[Link to Logs](https://app.netlify.com/sites/workhuman-next/deploys/65c25a12e9e90f000874c61a)
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>

```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>

```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>
