### ISSUE TITLE
Plugin "@netlify/plugin-nextjs" must not be specified twice in the app

### ISSUE THREAD

**Issue by jimlundblad** [netlify/next-runtime#2566]
when running 

```bash
netlify build
```

I'm getting: 

```bash
Netlify Build
────────────────────────────────────────────────────────────────

❯ Version
  @netlify/build 29.51.4

❯ Flags
  {}
  
  Configuration error
────────────────────────────────────────────────────────────────

  Error message
  When resolving config file opendesk__tina--next/netlify.toml:
  Plugin "@netlify/plugin-nextjs" must not be specified twice in the app
```

netlify-cli/17.33.5 darwin-x64 node-v20.12.2

├── @netlify/plugin-nextjs@5.6.0
├── next@14.2.4

```toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
```

This is similar to [https://answers.netlify.com/t/netlify-deploy-plugin-configuration-error/](https://answers.netlify.com/t/netlify-deploy-plugin-configuration-error/)
