### ISSUE TITLE
[Bug]: Invalid URL error when handling rewrite

### ISSUE THREAD

**Issue by chrishannaby** [netlify/next-runtime#915]
### Steps to reproduce

A customer forked the zones example from Next.js which uses rewrites to stitch together multiple micro-sites into a single site using the following config:

```
module.exports = {
  async rewrites() {
    return [
      {
        source: "/blog",
        destination: "https://with-zones-blog.netlify.app/blog",
      },
      {
        source: "/blog/:path*",
        destination: "https://with-zones-blog.netlify.app/blog/:path*",
      },
    ];
  },
};

```

This example is deployed at https://silly-edison-c456ac.netlify.app if you navigate to https://silly-edison-c456ac.netlify.app/blog you will see the following error:

```
{"errorType":"TypeError","errorMessage":"Invalid URL: https,http://with-zones-blog.netlify.app/blog","trace":["TypeError [ERR_INVALID_URL]: Invalid URL: https,http://with-zones-blog.netlify.app/blog","    at onParseError (internal/url.js:258:9)","    at new URL (internal/url.js:334:5)","    at new URL (internal/url.js:331:22)","    at Runtime.handler (/var/task/.netlify/functions-internal/___netlify-handler/___netlify-handler.js:137:22)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
```

### A link to a reproduction repository

https://github.com/chrishannaby/with-zones-netlify-redirect

### Plugin version

4.0.0-rc.0

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your `netlify.toml` file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
[build]
  environment = { NETLIFY_USE_YARN="true" }
  command = "yarn build"
  publish = ".next"

[dev]
  command = "yarn dev"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"```

</details>


### Relevant log output (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>
