### ISSUE TITLE
[Bug]: Pages are not redirected to url with trailing slash

### ISSUE THREAD

**Issue by vpreponen** [netlify/next-runtime#998]
### Steps to reproduce

1. Go to https://nifty-neumann-ecf646.netlify.app/arkisto
2. Page is not redirected to https://nifty-neumann-ecf646.netlify.app/arkisto/

If I run `yarn build && yarn export` in local the files are created as `arkisto/index.html`. On Netlify it looks like they are created as `arkisto.html`.

### A link to a reproduction repository

https://github.com/vpreponen/indyville/

### Plugin version

4.0.0

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### Your `netlify.toml` file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
[[redirects]]
  from = "/feed"
  to = "/feed.xml"
  status = 301
  force = true

[[redirects]]
  from = "/baari"
  to = "https://baari.indyville.fi/"
  status = 301
  force = true

[[redirects]]
  from = "/baari/*"
  to = "https://baari.indyville.fi/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/retro"
  to = "https://retro.indyville.fi/"
  status = 301
  force = true

[[redirects]]
  from = "/retro/*"
  to = "https://retro.indyville.fi/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/kuvat/*"
  to = "https://assets.indyville.fi/kuvat/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/jw_flv/*"
  to = "https://assets.indyville.fi/video/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/svg/*"
  to = "https://assets.indyville.fi/svg/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/tiedostot/*"
  to = "https://assets.indyville.fi/tiedostot/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/villen_muut_tiedostot/*"
  to = "https://vp.indyville.fi/files/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/metsapuhuu/*"
  to = "https://vp.indyville.fi/metsapuhuu/:splat"
  status = 301
  force = true
```

</details>

### Relevant log output (or link to your logs)

<details>
  <summary>Build logs</summary>
  
https://app.netlify.com/sites/nifty-neumann-ecf646/deploys/61b9c66dc562b20008e09ff6

</details>
